Primary constructor implement
ardalis/CleanArchitecture pull request #762
Opened 2024-07-06 13:28 UTC by KhanbalaRashidov

2024-07-08 19:34 UTC, ardalis commented on src/Clean.Architecture.Infrastructure/Data/AppDbContext.cs
> +  IDomainEventDispatcher? _dispatcher) : DbContext(_options)
These should not have `_` prefix.

2024-07-08 19:35 UTC, ardalis requested changes

2024-07-08 19:35 UTC, ardalis commented on src/Clean.Architecture.Infrastructure/Data/EfRepository.cs
> +public class EfRepository<T>(AppDbContext _dbContext) :
Remove `_` prefix on constructor parameters.

2024-07-08 19:35 UTC, ardalis commented on src/Clean.Architecture.Infrastructure/Email/MimeKitEmailSender.cs
> +  IOptions<MailserverConfiguration> _mailserverOptions) : IEmailSender
Remove `_` prefix

2024-07-08 19:35 UTC, ardalis commented on src/Clean.Architecture.Infrastructure/Email/SmtpEmailSender.cs
> +public class SmtpEmailSender(ILogger<SmtpEmailSender> _logger,
Remove `_`

2024-07-09 03:56 UTC, KhanbalaRashidov commented on src/Clean.Architecture.Infrastructure/Data/AppDbContext.cs
> +  IDomainEventDispatcher? _dispatcher) : DbContext(_options)
Okay

2024-07-09 04:01 UTC, KhanbalaRashidov commented on src/Clean.Architecture.Infrastructure/Email/MimeKitEmailSender.cs
> +  IOptions<MailserverConfiguration> _mailserverOptions) : IEmailSender
Resolve

2024-08-02 15:39 UTC, ardalis requested changes

2024-08-02 15:39 UTC, ardalis commented on src/Clean.Architecture.Infrastructure/Email/MimeKitEmailSender.cs
> +    logger.LogWarning("Sending email to {to} from {from} with subject {subject} using {type}.", to, from, subject, this.ToString());
Avoid using class level parameters directly - assign to _logger and use that.

2024-08-02 15:39 UTC, ardalis commented on src/Clean.Architecture.Infrastructure/Email/SmtpEmailSender.cs
> +    logger.LogWarning("Sending email to {to} from {from} with subject {subject} using {type}.", to, from, subject, this.ToString());
See above.

2024-08-03 01:13 UTC, ardalis commented on src/Clean.Architecture.Infrastructure/Email/MimeKitEmailSender.cs
> +    logger.LogWarning("Sending email to {to} from {from} with subject {subject} using {type}.", to, from, subject, this.ToString());
this.ToString() should really be `body`

2024-08-03 18:53 UTC, merged

2024-08-03 18:53 UTC, ardalis commented
Thanks!